apiVersion: v1
kind: Pod
metadata:
  name: two-container-pod
spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80
  - name: container-2
    image: alpine
    command: ['watch", "wget", "-q0-", "localhost"][minikube@centos8vm2 pods]$
